apply_climate_active:
	@./apply_climate_active.sh
apply_climate_off:
	@./apply_climate_off.sh
apply_lock_secured:
	@./apply_lock_secured.sh
apply_lock_unsecured:
	@./apply_lock_unsecured.sh
cache:
	@source common_cache.sh && cache
cleanup:
	@source common_cleanup.sh && cleanup
dump:
	@source common_dump.sh && dump
install: 
	@source common_install.sh && install
loading:
	@source common_loading.sh && loading
refresh:
	@source refresh.sh && refresh
reset:
	@source common_reset.sh && reset
screenshot:
	@source common_screenshot.sh && screenshot
setup:
	@source common_setup.sh && setup
get_battery_helper:
	@source get_battery_helper.sh && get_battery_helper
get_battery_state:
	@./get_battery_state.sh
get_cached_state:
	@./get_cached_state.sh
get_charging_helper:
	@source get_charging_helper.sh && get_charging_helper
get_charging_state:
	@./get_charging_state.sh
get_climate_helper:
	@source get_climate_helper.sh && get_climate_helper
get_climate_state:
	@./get_climate_state.sh
get_lock_helper:
	@source get_lock_helper.sh && get_lock_helper
get_lock_state:
	@./get_lock_state.sh
get_plug_helper:
	@source get_plug_helper.sh && get_plug_helper
get_plug_state:
	@./get_plug_state.sh
get_state:
	@./get_state.sh
helper_toggle_climate:
	@source helper_toggle_climate.sh && helper_toggle_climate
helper_toggle_lock:
	@source helper_toggle_lock.sh && helper_toggle_lock
copy:
	@rm -f ~/Developer/homebridge-polestar/scripts/*.sh
	@cp *.sh ~/Developer/homebridge-polestar/scripts/